main: k.tp.TPExtended
name: TPExtended
version: 1.2
commands:
    tpl:
        description: Teleports you with a lightning effect. Can be used in console when provided two players.
        usage: /tpl [player] <<otherplayer>|<x> <y> <z>>
    tpe:
        description: Teleports you with a explosion effect. Can be used in console when provided two players.
        usage: /tpe [player] <<otherplayer>|<x> <y> <z>>
    tps:
        description: Teleports you with a smoke effect. Can be used in console when provided two players.
        usage: /tpe [player] <<otherplayer>|<x> <y> <z>>